### ISSUE TITLE
Why are there empty interfaces

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail** [MohamedISoliman/android-MVI#1]
In the base package, most of the files are empty interfaces !!

Why do they exist ?

**Comment by mibrahimdev** [comment]
Hello Ahmed, I think we had this discussion before, and we agreed that doing interfaces for the sake of just doing it is a bad thing .. but I was discovering the pattern, and I think I'l try to minimize the effort to implement such a thing in production .. so the interfaces is just a parent types to abstract the code in future. 
if I didn't find a useful use of them I'll get rid of them .. Trust me :smile: .
